// Renders Notato's small icons (the Android SDK's path data, in a 24 box, stroked round) as white PNGs at 3x, and the
// potato at 120 px, then writes them as base64 into the React Native and Flutter SDKs, which tint them. macOS 14 or
// later (NSImage reads SVG): `swift scripts/icons/render.swift`.
import AppKit
import Foundation

let icons: [(String, String, Double)] = [
    ("crosshair", "M4 12a8 8 0 1 0 16 0a8 8 0 1 0-16 0M12 1.5V6M12 18v4.5M1.5 12H6M18 12h4.5", 1.8),
    ("close", "M6 6l12 12M18 6 6 18", 2.7),
    ("up", "M12 19V5M5 12l7-7 7 7", 2.2),
    ("eye", "M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12zM9 12a3 3 0 1 0 6 0a3 3 0 1 0-6 0", 2),
    ("eyeOff", "M2 2l20 20M10.7 5.1A10 10 0 0 1 12 5c6.5 0 10 7 10 7a13 13 0 0 1-1.7 2.7M6.6 6.6A13.5 13.5 0 0 0 2 12s3.5 7 10 7a9.7 9.7 0 0 0 5.4-1.6M9.9 9.9a3 3 0 1 0 4.2 4.2", 2),
    ("list", "M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01", 2),
    ("package", "M21 8 12 3 3 8v8l9 5 9-5zM3 8l9 5 9-5M12 13v8", 2),
    ("trash", "M3 6h18M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6M10 11v6M14 11v6M9 6V4h6v2", 2),
    ("sliders", "M4 21v-7M4 10V3M12 21v-9M12 8V3M20 21v-5M20 12V3M1 14h6M9 8h6M17 16h6", 2),
    ("minimize", "M8 3v3a2 2 0 0 1-2 2H3M21 8h-3a2 2 0 0 1-2-2V3M3 16h3a2 2 0 0 1 2 2v3M16 21v-3a2 2 0 0 1 2-2h3", 2),
    ("power", "M12 2v10M18.4 6.6a9 9 0 1 1-12.8 0", 2),
    ("chevronLeft", "M15 6l-6 6 6 6", 2.8),
    ("chevronRight", "M9 6l6 6-6 6", 2.8),
    ("users", "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M5 7a4 4 0 1 0 8 0a4 4 0 1 0-8 0M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75", 2),
    ("camera", "M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3zM9 13a3 3 0 1 0 6 0a3 3 0 1 0-6 0", 2),
]
let filled: [(String, String)] = [
    ("more", "<circle cx='5' cy='12' r='1.8'/><circle cx='12' cy='12' r='1.8'/><circle cx='19' cy='12' r='1.8'/>"),
    ("grip", (([6, 12, 18] as [Int]).map { "<circle cx='9' cy='\($0)' r='1.6'/><circle cx='15' cy='\($0)' r='1.6'/>" }).joined()),
]

/// Draws `image` into a new `size`-pixel square bitmap, as PNG data.
func pngData(_ image: NSImage, size: Int, interpolation: NSImageInterpolation = .default) -> Data {
    let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: size, pixelsHigh: size, bitsPerSample: 8, samplesPerPixel: 4,
                               hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)!
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
    NSGraphicsContext.current?.imageInterpolation = interpolation
    image.draw(in: NSRect(x: 0, y: 0, width: size, height: size))
    NSGraphicsContext.restoreGraphicsState()
    return rep.representation(using: .png, properties: [:])!
}

func png(svg: String, size: Int) -> Data {
    guard let image = NSImage(data: Data(svg.utf8)) else { fatalError("cannot read \(svg)") }
    return pngData(image, size: size)
}

func resized(_ url: URL, size: Int) -> Data {
    guard let image = NSImage(contentsOf: url) else { fatalError("no \(url.path)") }
    return pngData(image, size: size, interpolation: .high)
}

let root = URL(fileURLWithPath: CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : FileManager.default.currentDirectoryPath)
var out: [(String, String)] = []
for (name, d, width) in icons {
    let svg = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='72' height='72' fill='none' stroke='#fff' stroke-width='\(width)' stroke-linecap='round' stroke-linejoin='round'><path d='\(d)'/></svg>"
    out.append((name, png(svg: svg, size: 72).base64EncodedString()))
}
for (name, body) in filled {
    let svg = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='72' height='72' fill='#fff'>\(body)</svg>"
    out.append((name, png(svg: svg, size: 72).base64EncodedString()))
}
let potato = resized(root.appendingPathComponent("assets/notato.png"), size: 120).base64EncodedString()

let header = "Generated by scripts/icons/render.swift: white icons at 3x (24 points), tinted where they are drawn."
var ts = "// \(header)\n\n/** Notato's icons, as PNG data. */\nexport const ICONS = {\n"
for (name, data) in out { ts += "    \(name): \"data:image/png;base64,\(data)\",\n" }
ts += "} as const;\n\nexport type IconName = keyof typeof ICONS;\n\n/** The potato, 120 px. */\nexport const POTATO = \"data:image/png;base64,\(potato)\";\n"
try ts.write(to: root.appendingPathComponent("sdks/react-native/src/ui/icons.ts"), atomically: true, encoding: .utf8)

var dart = "// \(header)\n\n/// Notato's icons, as base64 PNG data.\nconst notatoIcons = <String, String>{\n"
for (name, data) in out { dart += "  '\(name)': '\(data)',\n" }
dart += "};\n\n/// The potato, 120 px.\nconst notatoPotato = '\(potato)';\n"
try dart.write(to: root.appendingPathComponent("sdks/flutter/lib/src/ui/icons.dart"), atomically: true, encoding: .utf8)
print("wrote \(out.count) icons")
