// @ts-nocheck: Bun types html and css imports as bundles, but with { type: "file" } they are paths.
// Generated by packages/board/scripts/build.ts. Do not edit; run `bun run build:board`.
import file0 from "../../board/dist/notato-ck12kfpk.png" with { type: "file" }
import file1 from "../../board/dist/index.html" with { type: "file" }
import file2 from "../../board/dist/index-e6epbsxf.js" with { type: "file" }
import file3 from "../../board/dist/index-yj80v7s9.css" with { type: "file" }
import file4 from "../../board/dist/inject.js" with { type: "file" }
import file5 from "../../board/dist/fonts/jetbrains-mono-latin-wght-normal.woff2" with { type: "file" }
import file6 from "../../board/dist/fonts/figtree-latin-wght-normal.woff2" with { type: "file" }
import file7 from "../../board/dist/fonts/bricolage-grotesque-latin-opsz-normal.woff2" with { type: "file" }
import file8 from "../../board/dist/fonts/bricolage-grotesque-latin-ext-opsz-normal.woff2" with { type: "file" }
import file9 from "../../board/dist/fonts/figtree-latin-ext-wght-normal.woff2" with { type: "file" }
import file10 from "../../board/dist/fonts/jetbrains-mono-latin-ext-wght-normal.woff2" with { type: "file" }

export const webAssets: Record<string, { path: string; type: string }> | null = {
  "notato-ck12kfpk.png": { path: file0, type: "image/png" },
  "index.html": { path: file1, type: "text/html; charset=utf-8" },
  "index-e6epbsxf.js": { path: file2, type: "text/javascript; charset=utf-8" },
  "index-yj80v7s9.css": { path: file3, type: "text/css; charset=utf-8" },
  "inject.js": { path: file4, type: "text/javascript; charset=utf-8" },
  "fonts/jetbrains-mono-latin-wght-normal.woff2": { path: file5, type: "font/woff2" },
  "fonts/figtree-latin-wght-normal.woff2": { path: file6, type: "font/woff2" },
  "fonts/bricolage-grotesque-latin-opsz-normal.woff2": { path: file7, type: "font/woff2" },
  "fonts/bricolage-grotesque-latin-ext-opsz-normal.woff2": { path: file8, type: "font/woff2" },
  "fonts/figtree-latin-ext-wght-normal.woff2": { path: file9, type: "font/woff2" },
  "fonts/jetbrains-mono-latin-ext-wght-normal.woff2": { path: file10, type: "font/woff2" },
}
